import React, { useEffect } from 'react';
import { View, Text, TextInput, TouchableOpacity, StyleSheet, ScrollView } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useDispatch, useSelector } from 'react-redux';
import { Formik } from 'formik';
import { Picker } from '@react-native-picker/picker';
import Toast from 'react-native-toast-message';
import { farmerSchema } from '../../validation/schemas';
import { fetchFarmers, createFarmer } from '../../redux/slices/farmerSlice';

const AddFarmerScreen = ({ navigation, route }) => {
  const insets = useSafeAreaInsets();
  const dispatch = useDispatch();
  const token = useSelector((state) => state.auth.token);
  const selectedCenterId = route?.params?.centerId || '';
  const selectedCenterName = route?.params?.centerName || '';
  const selectedCenterCode = route?.params?.centerCode || '';

  return (
    <ScrollView
      style={styles.container}
      contentContainerStyle={[styles.content, { paddingTop: insets.top + 12 }]}
      keyboardShouldPersistTaps="handled"
      showsVerticalScrollIndicator={false}
    >
      <Text style={styles.title}>Add Farmer</Text>
      <Formik
        initialValues={{
          fullName: '',
          mobileNumber: '',
          ifscCode: '',
          accountNumber: '',
          confirmAccountNumber: '',
          accountHolderName: '',
          assignedCenter: selectedCenterId,
          assignedCenterCode: selectedCenterCode,
          animalType: 'Cow',
          status: 'Active',
        }}
        validationSchema={farmerSchema}
        onSubmit={async (values) => {
          try {
            const { confirmAccountNumber: _ca, ...payload } = values;
            await dispatch(createFarmer({ data: payload, token })).unwrap();
            Toast.show({ type: 'success', text1: 'Success', text2: 'Farmer added successfully', position: 'top', visibilityTime: 3000 });
            navigation.navigate('FarmerList', {
              centerId: selectedCenterId,
              centerCode: selectedCenterCode,
              centerName: selectedCenterName,
              refresh: Date.now(),
            });
          } catch (error) {
            Toast.show({ type: 'error', text1: 'Error', text2: error, position: 'top', visibilityTime: 4000 });
          }
        }}
      >
        {({ handleChange, handleBlur, handleSubmit, values, errors, touched }) => (
          <>
            {/* Auto-generated code - will be generated by backend */}
            <View style={styles.field}>
              <Text style={styles.label}>Farmer Code (Auto Generated)</Text>
              <TextInput 
                value="Auto-generated by system" 
                style={[styles.input, styles.readOnlyInput]} 
                editable={false} 
              />
            </View>

            {/* Basic Info */}
            <Text style={styles.sectionLabel}>Basic Information</Text>
            {[
              { name: 'fullName', label: 'Full Name' },
              { name: 'mobileNumber', label: 'Mobile Number', keyboard: 'phone-pad' },
            ].map((field) => (
              <View key={field.name} style={styles.field}>
                <Text style={styles.label}>{field.label}</Text>
                <TextInput
                  value={values[field.name]}
                  onChangeText={handleChange(field.name)}
                  onBlur={handleBlur(field.name)}
                  placeholder={field.label}
                  keyboardType={field.keyboard || 'default'}
                  style={styles.input}
                  placeholderTextColor="#94a3b8"
                />
                {touched[field.name] && errors[field.name] ? <Text style={styles.error}>{errors[field.name]}</Text> : null}
              </View>
            ))}

            {/* Bank Details */}
            <Text style={styles.sectionLabel}>Bank Details</Text>
            {[
              { name: 'ifscCode', label: 'IFSC Code', caps: 'characters' },
              { name: 'accountNumber', label: 'Account Number', keyboard: 'numeric' },
              { name: 'confirmAccountNumber', label: 'Confirm Account Number', keyboard: 'numeric' },
              { name: 'accountHolderName', label: 'Account Holder Name' },
            ].map((field) => (
              <View key={field.name} style={styles.field}>
                <Text style={styles.label}>{field.label}</Text>
                <TextInput
                  value={values[field.name]}
                  onChangeText={handleChange(field.name)}
                  onBlur={handleBlur(field.name)}
                  placeholder={field.label}
                  keyboardType={field.keyboard || 'default'}
                  autoCapitalize={field.caps || 'none'}
                  style={styles.input}
                  placeholderTextColor="#94a3b8"
                />
                {touched[field.name] && errors[field.name] ? <Text style={styles.error}>{errors[field.name]}</Text> : null}
              </View>
            ))}

            {/* Dairy Details */}
            <Text style={styles.sectionLabel}>Dairy Details</Text>
            <View style={styles.field}>
              <Text style={styles.label}>Animal Type</Text>
              <View style={styles.pickerWrap}>
                <Picker selectedValue={values.animalType} onValueChange={handleChange('animalType')}>
                  <Picker.Item label="Cow" value="Cow" />
                  <Picker.Item label="Buffalo" value="Buffalo" />
                  <Picker.Item label="Both" value="Both" />
                </Picker>
              </View>
              {touched.animalType && errors.animalType ? <Text style={styles.error}>{errors.animalType}</Text> : null}
            </View>
            <View style={styles.field}>
              <Text style={styles.label}>Status</Text>
              <View style={styles.pickerWrap}>
                <Picker selectedValue={values.status} onValueChange={handleChange('status')}>
                  <Picker.Item label="Active" value="Active" />
                  <Picker.Item label="Inactive" value="Inactive" />
                </Picker>
              </View>
              {touched.status && errors.status ? <Text style={styles.error}>{errors.status}</Text> : null}
            </View>

            <TouchableOpacity style={styles.button} onPress={handleSubmit}>
              <Text style={styles.buttonText}>Create Farmer</Text>
            </TouchableOpacity>
          </>
        )}
      </Formik>
    </ScrollView>
  );
};

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#f8fafc' },
  content: { padding: 20 },
  title: { fontSize: 22, fontWeight: '800', color: '#0f172a', marginBottom: 18 },
  sectionLabel: { marginTop: 12, marginBottom: 8, color: '#334155', fontWeight: '700', fontSize: 15 },
  field: { marginBottom: 14 },
  label: { marginBottom: 6, color: '#334155', fontWeight: '600', fontSize: 13 },
  input: {
    height: 50, backgroundColor: '#fff', borderRadius: 14,
    borderWidth: 1, borderColor: '#cbd5e1', paddingHorizontal: 16, color: '#0f172a', fontSize: 15,
  },
  readOnlyInput: { backgroundColor: '#e2e8f0', color: '#334155' },
  pickerWrap: { backgroundColor: '#fff', borderRadius: 14, borderWidth: 1, borderColor: '#cbd5e1', overflow: 'hidden' },
  button: { backgroundColor: '#2563eb', borderRadius: 14, alignItems: 'center', justifyContent: 'center', height: 50, marginTop: 16 },
  buttonText: { color: '#fff', fontWeight: '700', fontSize: 16 },
  error: { color: '#dc2626', marginTop: 4, fontSize: 12 },
});

export default AddFarmerScreen;
